### ISSUE TITLE
Does sync work with YouTrack 2018.2?

### ISSUE THREAD

**Issue by aaronwardle** [extempl/youtrack-support-for-harvest-extension#2]
Hi

Thanks for creating this great plugin we are just switching over to YouTrack and would love to still track time with Harvest. 

So far I have installed the extension in Chrome and I can easily click a button in YouTrack to track time for the issue, however, the time from Harvest never syncs back into YouTrack.

I have populated the settings with the URLs and login but nothing seems to happen even when I click the extension. 

Thanks

**Comment by aaronwardle** [comment]
It's working now, I restarted Chrome and it started to work 👍

**Comment by extempl** [comment]
Yeah, YT login session there is bit tricky. Hadn't time to implement through JetBrains Hub API yet. 
Basically it opens YT window in a background to get actual session, and on this step there may be some issues. Should help also just open YT on a separate tab if it doesn't sync anymore.

**Comment by aaronwardle** [comment]
Ah that's good to know and thanks for the quick reply, we will keep an eye on it and if its still causing issues I will see if one of our developers can take a look at it and submit a pull request.

**Comment by chiragtailor** [comment]
@extempl I believe this issue is back again, it doesnt seem to sync the time with youtrack

**Comment by extempl** [comment]
@chiragtailor Let me recheck.

**Comment by chiragtailor** [comment]
@extempl Thanks it will really be appreciated if it starts to work again.

**Comment by extempl** [comment]
@chiragtailor Just checked. It has some issues, but still works :)
Things you should take into account - there should be exactly same workType in YT and Harvest. If there is some event tracked and has workType that not exists in YT - YT will return 400 error on update try. 
Also, there may be a situation when the session for extension is lost, which should be fixed when you reloading YT page (assumed you do it from time to time).
Also, make sure every field is highlighted green in extension options. 

If you still have any issues, open the extensions list, set on developer mode and click on the `Inspect views
background page` in the appropriate extension block. 
Then click on the extension icon in the browser's extensions-bar, this should trigger force update. You'll see the result in the developer tools for the background page of the extension. Share them here if won't be able to fix.

**Comment by extempl** [comment]
@chiragtailor Hey there. Just checking - everything works on your end or you're not using it anymore?
